name: myportfolio
description: Saujan Bindukar Portfolio.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^11.0.0
  flutter_riverpod: ^2.4.1
  go_router: ^11.1.1
  freezed: ^2.4.3
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14

  cupertino_icons: ^1.0.2
  freezed_annotation: 
  firebase_core:
  firebase_analytics:
  firebase_crashlytics:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/intro1.svg
    - assets/images/about.svg
    - assets/images/projects.svg
    - assets/images/contacts.svg
    - assets/images/skills.svg
    - assets/project_icons/
    - assets/social_icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 500
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf
